### ISSUE TITLE
Errors while installing

### ISSUE THREAD

**Issue by cmabastar** [jayclassless/setup-poetry-action#162]
Hello, Recently i got an error in my ci/cd

<img width="876" alt="image" src="https://github.com/jayclassless/setup-poetry-action/assets/4414453/09ef2a1a-5150-4d9b-a7e1-05af675fb29f">

Any ideas?

**Comment by jayclassless** [comment]
Poetry finally retired the very-old method of downloading their installation script.

I've updated it to the current URL. It should work better now.
